<?php
session_start();
unset($_SESSION['cart']);
unset($_SESSION['total']);
unset($_SESSION['email']);
unset($_SESSION['firstName']);
unset($_SESSION['lastName']);
unset($_SESSION['address']);
header('location:index.php');
?>